### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by ndelangen** [wallabyjs/atom-wallaby#52]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:24)
DisplayMarkerLayer.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:94:62)
TextEditor.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1761:38)
Function.value (/Users/dev/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:21511)
<unknown> (/Users/dev/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:19612)
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published.

**Comment by LL782** [comment]
I just installed atom-wallaby and when I check for updates none are found, yet I'm still getting this depreciation warning. @ArtemGovorov can you advise how I can get the published fix please.

**Comment by ArtemGovorov** [comment]
@LL782 Please 
- paste the full error deprecations warning (with the stack),
- open Atom Dev Tools (`Cmd + Shift + I`) and paste the versions of the wallaby Atom plugin and wallaby Core.

**Comment by LL782** [comment]
@ArtemGovorov 

Full warning with stack:
```
Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

Function.extractParams - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markPosition - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:223:24
DisplayMarkerLayer.markBufferPosition - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:109:52
TextEditor.markBufferPosition - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1784:38
Function.value - /Users/laurence.lord/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:22260
<unknown> - /Users/laurence.lord/.atom/packages/atom-wallaby/wallaby-atom/index.js:14:20243
```

From console:
```
Wallaby Console: Atom plugin v1.0.34
wallaby.js [sm]:79 Wallaby Console: Core v1.0.441
index.js:14 Wallaby Console: Started Wallaby.js Core v1.0.441
```


Atom-wallaby package: 1.0.17 (according to Atom > Settings > Packages)
Atom version: 1.15.0 x64  (according to Atom > About)

**Comment by ArtemGovorov** [comment]
@LL782 Thanks for providing the details. The issue was fixed for Atom versions >= 1.16. Since you are using 1.15, the deprecation warning is harmless and you can just ignore it. If you decide to migrate to a newer version of Atom (1.16, 1.17, 1.18, 1.19-beta), then the warning will just disappear.
